### ISSUE TITLE
Colors required for printing 

### ISSUE THREAD

**Issue by kambasana** [JanLahmann/RasQberry-Two-3Dmodel#1]
I may be missing something but could you specify the colours required to print so we can be accurate to what you have done when printing in this repo

**Comment by JanLahmann** [comment]
Thank you for your feedback, @kambasana !
Documentation can be found in our main repo: https://rasqberry.org
Filament colours are listed in the "Core Components BOM": https://rasqberry.org/3d-model/bill-of-materials
Build instructions are at: https://rasqberry.org/3d-model/hardware-assembly-guide
